# week08/k8s/order-service.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-w08e1
  labels:
    app: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      # [MOD] allow the pod to pull from ACR using the secret created by the workflow
      imagePullSecrets:
        - name: acr-pull

      containers:
      - name: order-service-container
        # [MOD] point to your ACR (w08tmtlt)
        image: w08tmtlt.azurecr.io/order_service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8001
        env:
        # Database connection details
        - name: POSTGRES_HOST
          value: order-db-service-w08e1
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: ecomm-config-w08e1
              key: ORDERS_DB_NAME
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: ecomm-secrets-w08e1
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ecomm-secrets-w08e1
              key: POSTGRES_PASSWORD

        # Internal URL to Product API (ClusterIP service)
        - name: PRODUCT_SERVICE_URL
          value: http://product-service-w08e1:8000

---
apiVersion: v1
kind: Service
metadata:
  name: order-service-w08e1
  labels:
    app: order-service
spec:
  selector:
    app: order-service
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
  type: LoadBalancer
