apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-w08e1
  labels:
    app: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      imagePullSecrets:
        - name: acr-pull
      containers:
      - name: order-service-container
        image: w08tmtlt.azurecr.io/order_service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8001
        env:
        - name: POSTGRES_HOST
          value: order-db-service-w08e1
        - name: POSTGRES_PORT               # [MOD]
          value: "5432"
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: ecomm-config-w08e1
              key: ORDERS_DB_NAME
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: ecomm-secrets-w08e1
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ecomm-secrets-w08e1
              key: POSTGRES_PASSWORD
        - name: PRODUCT_SERVICE_URL
          value: http://product-service-w08e1:8000

        # [MOD] health probes
        readinessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 15
          periodSeconds: 5
          failureThreshold: 12
        livenessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 45
          periodSeconds: 10
